#!/bin/bash
# filepath: /home/Poppie/Desktop/Code/assignment-5-Priyanshu-Shah-p1/server/aesdsocket-start-stop

DAEMON=/home/Poppie/Desktop/Code/assignment-5-Priyanshu-Shah-p1/server/aesdsocket
PIDFILE=/var/run/aesdsocket.pid

case "$1" in
    start)
        echo "Starting aesdsocket..."
        start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- -d
        ;;
    stop)
        echo "Stopping aesdsocket..."
        start-stop-daemon --stop --pidfile $PIDFILE --signal SIGTERM
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0